### PR TITLE
propose: separated directory for schemas

### PR DESCRIPTION
**Pull request by PavelVesnin**
purpose: separated directory for schemas

### CODE REVIEW

**Comment by AndrewDryga** [comment]
This is actually an anti-pattern when we talk about [bounded context](https://martinfowler.com/bliki/BoundedContext.html) that we trying to apply along with Phoenix 1.3. 

Separating schemas for each context decouples application source and simplifies change management or even splinting one application into umbrella when it starts to grow. 

But we will definitely need some time to get used to it.

**Comment by PavelVesnin** [comment]
you're right. So i created context for MSP and Relations (maybe it should be renamed?)

**Comment by AndrewDryga** [comment]
Lets take `capitation_contract` for example, it's hard to tell now should it be part of MSP or not, because eventually we will grow logic around it. And we might need to decouple it, so why do we making decisions to couple this stuff right now?

And actually `declaration` (and rest in `related`) is a part of `msp`-related code and should be handled in a same way as stuff that you place into `msp/`. 

P.S.: Don't create paths like `msp/msp.ex`, `msp.ex` in this case should be in lib.

**Comment by gmile** [comment]
Why `doctor.ex` schema is not moved?

I followed the most basic principle when making `msp` and `doctor` services: just put the schema and API to working with it – in the same folder. Reason: I don't have a strong opinion regarding where to put the stuff yet, and sample of directly structure provided with phoenix 1.3-rc0 somewhat suggested similar approach.

I believe at the moment we have limited knowledge about our entities and contexts they belong to. Specially given the fact that just today it was said that a much bigger and mode detailed picture is coming right after the demo.

Therefor, **I'd go with something most basic that will work for some time**.

Obviously at some point in future as soon as we have tens of DB tables, simple approach will stop scaling for us, and start slowing us down – at that point we definitely should revisit the issue.

I think we shouldn't worry too much about where to place schema files right now. Any of the below will work for me:

1. keep API and schema in the same folder,
2. keep all schemas altogether in a single folder somewhere in the project tree

    We should not be dealing with schemas directly per Phoenix 1.3, dealing with them only by means of "internal APIs" aka _contexts_. So why not just shelve them in the way we always shelve migrations

**Pull request closed without merging**
